# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012a5b75d63d7a6c61200eabbf100b3c9d151f61acdfb58ce8130d41ec3ddace487cfdfb5e185fc675de8debfa117d453894b40a61daed4c4f6b53ddb771d8dd

test:
  secret_key_base: 43fc94ebe61d9cc4407c5a35e2719f031b3158b3db05d14bfa81c954810676e7664f10c9f598f1724c4a277286173cfa258a3d016af6ebf1bfb24700f7dc8f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
